### ISSUE TITLE
Question: Run within Django?

### ISSUE THREAD

**Issue by vidstige** [chris104957/django-carrot#71]
Can I somehow spawn the carrot process from within Django? Currently I'm running the django app in a container, and it would be convenient to just have to launch one process. If not, would you consider PRs for fixing something like this.

**Comment by chris104957** [comment]
Hi, we actually deploy django-carrot, django and nginx using docker-compose as follows:
```yaml
version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - /usr/src/app
      - /usr/src/app/static
    command:
      /usr/local/bin/gunicorn project.wsgi:application -w 2 -b :8000 --env DJANGO_SETTINGS_MODULE=project.docker_settings

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  carrot:
    build: ./web
    volumes:
     - /usr/src/app
    depends_on:
      - web
    command:
      python manage.py carrot
```

Note that we are using ``python manage.py carrot`` and **not** ``python3 manage.py carrot_daemon start`` here
