### ISSUE TITLE
carrot just exits

### ISSUE THREAD

**Issue by vidstige** [chris104957/django-carrot#74]
I'm trying to run carrot + django + postgres + rabbitmq in a docker-compose, but carrot just bails out successfully with exit code 0...  My docker-compose.yml file looks like this

```yml
version: '2'

services:
  rabbit:
    image: 'rabbitmq:3.7-alpine'
    expose:
      - "5672"

  postgres:
    image: 'postgres:9.6'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    restart: always
    build: ./
    depends_on:
      - postgres
      - rabbit
    expose:
      - "8000"
    ports:
      - "0.0.0.0:8000:8000"

  carrot:
    build: ./
    depends_on:
      - django
      - rabbit
    command:
      bash -c "sleep 8" && python manage.py carrot --traceback

volumes:
  postgres_data:

```

The container does not seem to produce any output whatsoever. There is no file in `/var/log/carrot.log` either. Please advice.

I fixed up another simpler django-leek yesterday, but today I saw you had fixed some stuff with the migrations, etc, so I thought I'd give carrot another try as I like the monitor and so on. However, I cannot seem to get it running at all.
